### ISSUE TITLE
Error in Example (segmentation of T1w image)

### ISSUE THREAD

**Issue by lcscosta** [jhuguetn/cat12-docker#1]
Hi @jhuguetn, thank you for creating a docker image for CAT12.

Unfortunately I got an error with the example in documentation. 

I run the command *sudo docker run -it --rm -v /home/user/data:/data jhuguetn/cat12 -b /opt/spm/standalone/cat_standalone_segment.txt /data/t1.nii*

and got the following output

`
grep: /opt/spm/standalone/cat_standalone_segment.txt: No such file or directory
grep: /opt/spm/standalone/cat_standalone_segment.txt: No such file or directory
grep: /opt/spm/standalone/cat_standalone_segment.txt: No such file or directory
grep: /opt/spm/standalone/cat_standalone_segment.txt: No such file or directory
Setting up environment variables
LD_LIBRARY_PATH is .:/opt/mcr/v93/runtime/glnxa64:/opt/mcr/v93/bin/glnxa64:/opt/mcr/v93/sys/os/glnxa64:/opt/mcr/v93/sys/opengl/lib/glnxa64
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/connectivity/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/external/signal/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/external/stats/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/fileio/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/forward/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/inverse/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/plotting/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/preproc/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/specest/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/statfun/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/trialfun/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/fieldtrip/utilities/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/ricoh_meg_reader/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/external/yokogawa_meg_reader/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/matlabbatch/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/toolbox/DAiSS/private
Warning: Private directories not allowed in MATLAB path: /opt/spm/spm12_mcr/home/gaser/spm12/toolbox/TSSS/private
SPM12, version 7771 (standalone)
MATLAB, version 9.3.0.713579 (R2017b)
 ___  ____  __  __                                            
/ __)(  _ \(  \/  )                                           
\__ \ )___/ )    (   Statistical Parametric Mapping           
(___/(__)  (_/\/\_)  SPM12 - https://www.fil.ion.ucl.ac.uk/spm/
Undefined function or variable 'mysubs_fields'.
Error in cfg_branch (line 59)
Error in cfg_getfile>reg_filter (line 1185)
Error in cfg_getfile (line 177)
Error in spm_select (line 115)
Error in spm_select (line 110)
Error in spm_select (line 97)
Error in spm_jobman (line 173)
Error in spm_standalone (line 95)
MATLAB:UndefinedFunction
`
Changing /opt/spm/standalone/cat_standalone_segment.txt  to /opt/spm/standalone/cat_standalone_segment.m avoid the error of *No such file or directory.*

Do you have any idea how to solve this undefined function problem?

**Comment by jhuguetn** [comment]
You are completely right @lcscosta, that's a typo in the example command.  

I have fixed the `README.md` file accordingly and I've also updated CAT 12.8 standalone version to the latest stable revision since there were some known -yet unresolved- problems with it (see #2 for details).  

I've just tagged and published the latest (`r1933`) version of the dockerized CAT12 app in [Docker Hub](https://hub.docker.com/r/jhuguetn/cat12/tags). You should be good to go now if you update it as follows,
```
docker pull jhuguetn/cat12:r1933
```

Thanks!

**Comment by lcscosta** [comment]
Thank you, now the docker image is running perfectly.
