### ISSUE TITLE
Selecting registration method

### ISSUE THREAD

**Issue by ndrewvo** [jhuguetn/cat12-docker#12]
Hi, I wanted to ask if it was possible to use the DARTEL instead of the Shooting method for registration using the containerized version of `cat12`. I am trying to generate deformation-based morphometry maps from T1w images, and this only works with the former and not the latter registration method.

I can choose the registration method in the standard version via the GUI in expert mode. For the containerized version, I've tried adding the following lines to my batch code:
`-a "matlabbatch{1}.spm.tools.cat.estwrite.extopts.registration.regmethod.shooting.regstr = 0;"`
`-a "matlabbatch{1}.spm.tools.cat.estwrite.output.jacobianwarped = 1;"`
...this generates a DBM map but still uses the default shooting method.

Thanks in advance for your help!

Andrew

**Comment by jhuguetn** [comment]
Hi Andrew, 

I believe this is available as an expert mode option in CAT12, ie. switching the spatial registration method (`Shooting` being the default option). You may just want to try adding the following to your segmentation script,
```
matlabbatch{1}.spm.tools.cat.estwrite.extopts.registration.regmethod.dartel.darteltpm = {'/opt/spm/spm12_mcr/home/gaser/gaser/spm/spm12/toolbox/cat12/templates_MNI152NLin2009cAsym/Template_1_Dartel.nii'};
```
...and get rid of the Shooting options,
```
%matlabbatch{1}.spm.tools.cat.estwrite.extopts.registration.regmethod.shooting.shootingtpm = {fullfile(fileparts(mfilename('fullpath')),'templates_MNI152NLin2009cAsym','Template_0_GS.nii')};
%matlabbatch{1}.spm.tools.cat.estwrite.extopts.registration.regmethod.shooting.regstr = 0.5;
```

Let me know if this helps, you should be able to do so since DARTEL is a toolbox included in the containerized version of CAT12.

**Comment by ndrewvo** [comment]
Hi @jhuguetn, could you please clarify how I would go about getting rid of the shooting options? I tried to go into the container and comment out those lines but those scripts are read-only. Or did you mean I should add those two lines but change their values to 0? Thanks!

**Comment by jhuguetn** [comment]
An straightforward way to achieve this, @ndrewvo, is to inject your own/modified batch files (aka MATLAB scripts) to the container in a mounted volume and run them as follows,
```
docker run -it --rm -v `pwd`/data:/data -v `pwd`/scripts:/scripts jhuguetn/cat12 \
 -b /scripts/modified_cat_standalone_segment.m \
 /data/my_dataset/sub-0001/anat/sub-0001_T1w.nii
```
In fact that was my idea from the beginning, to use those official standalone scripts as mere templates being able to locally derive and modify them at my will when needed. 

Hope it helps.

**Comment by ndrewvo** [comment]
Thanks for your help, @jhuguetn! The container is generating the expected DBM output now.
