### ISSUE TITLE
File permission

### ISSUE THREAD

**Issue by araikes** [jhuguetn/cat12-docker#7]
Thanks for this tool.

I pulled it today and am testing it using singularity. Segmentation appears to work ok but when running surface segmentation, I receive the following:

```
  Create initial surface                                          /bin/bash: /opt/spm/spm12_mcr/home/gaser/gaser/spm/spm12/toolbox/cat12/CAT.glnx86/CAT_SeparatePolygon: Permission denied

WARNING: Surface processing will not work because
(1) CAT binaries are not compatible to your system or
(2) File permissions are not correct (for unix use chmod a+x) or
(3) Antivirus software in Windwos or Gatekeeper in MAC OS is blocking to execute binaries
```

**Comment by jhuguetn** [comment]
Hi @araikes, I am not using singularity in a regular basis but I tried it and could indeed reproduce the issue. It seems related to #4 (044ccdf).  
Stay tuned, when possible will release a version with compiled binary files runnable so the image is usable with Singularity as well.

**Comment by araikes** [comment]
Thanks

**Comment by jhuguetn** [comment]
This issue should be fixed in the latest release, see https://github.com/jhuguetn/cat12-docker/releases/tag/r2166. You can pull it from DockerHub,
```
docker pull jhuguetn/cat12:latest
```

**Comment by araikes** [comment]
Ran to complete @jhuguetn.

Thanks
